[env:rpipicow]
platform   = https://github.com/maxgerhardt/platform-raspberrypi.git
board      = rpipicow
framework  = arduino

lib_deps =
    WiFi
    HTTPClient
    ArduinoJson@^7.0.0

monitor_speed = 115200
upload_protocol = picotool
